### ISSUE TITLE
Windows bash wrapping

### ISSUE THREAD

**Issue by japborst** [equinusocio/hyper-material-theme#12]
In Windows when using bash, wrapping doesn't work properly. Instead of going onto the next line, it continuous on the same line but at the beginning.

Perhaps some Unix / Windows differences? It works properly in cmd, just not in bash.

**Comment by equinusocio** [comment]
You have the same issue disabling this theme?

**Comment by japborst** [comment]
No, that's why I reported it here instead of in the hyper repo

**Comment by equinusocio** [comment]
It's strange because this theme doesn't change anything but tabs

**Comment by japborst** [comment]
It seemed to be isolated to this theme, as disabling seemed to solve the issue. However, the issue started occurring again. Have some hints where it goes wrong, will file an issue in the main repo. Thanks :)
