### ISSUE TITLE
Enable Vibrance Causing Text Ghosting

### ISSUE THREAD

**Issue by Xuraiis** [equinusocio/hyper-material-theme#15]
Please see below.

**Comment by equinusocio** [comment]
What do you mean with "Text Ghosting". Please add more details and screenshots

**Comment by Xuraiis** [comment]
Sorry, here:

When the transparent background is enabled, scrolling or doing any action that updates the state of a character cell, often doesn't clear the cell before rendering the new state.

Oddly enough though, I am not able to directly take screenshots - This causes it all to update prior to the screen being captured. So here is one via an external camera...

Transparency enabled:

![img_1940](https://cloud.githubusercontent.com/assets/18094011/26424727/7dfbd654-40d2-11e7-8312-99b8806d5fd6.JPG)

<img width="386" alt="screen shot 2017-05-24 at 10 45 40 pm" src="https://cloud.githubusercontent.com/assets/18094011/26424802/c14f8054-40d2-11e7-8167-f1c78d5f46d6.png">

Not enabled:

<img width="1075" alt="screen shot 2017-05-24 at 10 33 13 pm" src="https://cloud.githubusercontent.com/assets/18094011/26424739/8b75ed88-40d2-11e7-9bf9-a3c1caeb8ac1.png">

<img width="395" alt="screen shot 2017-05-24 at 10 33 26 pm" src="https://cloud.githubusercontent.com/assets/18094011/26424772/abe5d498-40d2-11e7-9c1d-0733887ae3bf.png">

**Comment by equinusocio** [comment]
I'm refactoring all the theme, so i will fix this issue next release. For now disable the vibrancy.
