### ISSUE TITLE
Copyright and licensing of this software

### ISSUE THREAD

**Issue by dkfiresky** [equinusocio/hyper-material-theme#18]
Your repository shares common code lines from the https://github.com/dkfiresky/hyper-macos repository.

This commit (https://github.com/equinusocio/hyper-material-theme/commit/987f5864785505cf185ce553f389b6a2930c9019) contains parts of code taken from https://github.com/dkfiresky/hyper-macos/blob/master/index.js.

As original repository's [license](https://github.com/dkfiresky/hyper-macos/blob/master/LICENSE) states:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Please preserve the original copyright and license notices provided in the [LICENSE](https://github.com/dkfiresky/hyper-macos/blob/master/LICENSE) file.

**Comment by equinusocio** [comment]
No problem, i just rewritten the code. have a nice day.
