### ISSUE TITLE
Plugin load error [zeit/hyper/issues/191]

### ISSUE THREAD

**Issue by RemiVillien** [equinusocio/hyper-material-theme#19]
Hello,

I don't know why, I get this error, and the theme don't work :/

```
Error: Cannot find module '/Users/remivillien/.hyper_plugins/node_modules/hyper-material-theme'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Applications/Hyper.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at le.plugins.concat.map.ce (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:8876)
    at Array.map (native)
    at se (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:8830)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:10365)
    at __webpack_require__ (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:1:119)
    at Object.<anonymous> (file:///Applications/Hyper.app/Contents/Resources/app/dist/bundle.js:47:368728)le.plugins.concat.map.ce @ bundle.js:1
bundle.js:1 [Notification] Plugin load error: "hyper-material-theme" failed to load in the renderer process. Check Developer Tools for details.

[Notification] Plugin load error: "hyper-material-theme" failed to load in the renderer process. Check Developer Tools for details.

index.html:35 total init time 162.32500000000002

bundle.js:47 Unimplemented DEC Private Mode: 1034```

**Comment by equinusocio** [comment]
Can you try this steps?

1. Remove **hyper-material-theme** from your plugins list
2. Restart hyper
3. Add again **hyper-material-theme** 
4. Restart again
5. Check the plugin version

**Comment by senorsancho** [comment]
I'm having the same issue as well. I tried the solution above but it did not work.

**Comment by equinusocio** [comment]
As temp fix, navigate to `~/.hyper_plugins/node_modules` and run `npm i hyper-material-theme`inside this folder.

**Comment by nonsocode** [comment]
I have a slightly similar issue.

After installing material theme, hyper doesn't load. The GUI disappears. this is the output in the console.
```
C:\Users\Nonso\AppData\Local\hyper\app-1.3.3\resources\electron.asar\renderer\api\remote.js:217 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot read property 'theme' of undefined
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Cannot read property 'theme' of undefined
    at callFunction (C:\Users\Nonso\AppData\Local\hyper\app-1.3.3\resources\electron.asar\browser\rpc-server.js:235:11)
    at EventEmitter.<anonymous> (C:\Users\Nonso\AppData\Local\hyper\app-1.3.3\resources\electron.asar\browser\rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\Nonso\AppData\Local\hyper\app-1.3.3\resources\electron.asar\browser\api\web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)metaToValue @ C:\Users\Nonso\AppData\Local\hyper\app-1.3.3\resources\electron.asar\renderer\api\remote.js:217(anonymous function) @ bundle.js:47__webpack_require__ @ bundle.js:1(anonymous function) @ bundle.js:1(anonymous function) @ bundle.js:1
index.html:35 total init time 485.75
```
I've removed and installed the theme multiple times but there's no difference.

**Comment by equinusocio** [comment]
@nonsocode https://github.com/equinusocio/hyper-material-theme/issues/19#issuecomment-309263988

**Comment by leovarmak** [comment]
@equinusocio After I installed this theme it broke my Hyper. Now the Hyperterm doesn't popup at all

**Comment by ericmarkmartin** [comment]
For some, this may not be an issue with this plugin but hyperterm itself. Right now, it seems that npm 5 and up do not automatically install plugins, although it is being worked on.

**Comment by yurynix** [comment]
Followed EDIT 3 in 
https://github.com/equinusocio/hyper-material-theme/issues/19#issuecomment-309263988

Getting on startup:
```
Uncaught Exception:
TypeError: Cannot read property 'theme' of undefined
    at Object.exports.decorateConfig.config [as decorateConfig] (/Users/yury/.hyper_plugins/node_modules/hyper-material-theme/index.js:17:18)
    at modules.forEach.plugin (/Applications/Hyper.app/Contents/Resources/app/plugins.js:345:30)
    at Array.forEach (native)
    at decorateObject (/Applications/Hyper.app/Contents/Resources/app/plugins.js:343:11)
    at Object.exports.getDecoratedConfig (/Applications/Hyper.app/Contents/Resources/app/plugins.js:367:10)
    at install (/Applications/Hyper.app/Contents/Resources/app/plugins.js:225:50)
    at updatePlugins (/Applications/Hyper.app/Contents/Resources/app/plugins.js:75:3)
    at Timeout.setTimeout (/Applications/Hyper.app/Contents/Resources/app/plugins.js:169:5)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

**Comment by equinusocio** [comment]
@yurynix Do you have Material Theme 2.0.5 and the config objects inside your hyper.js?
```js
MaterialTheme: {
      theme: 'Darker',
      backgroundOpacity: '0.8',
      accentColor: '#64FFDA',
      vibrancy: 'dark'
},
```

**Comment by yurynix** [comment]
I repeated the process, and put the config you mentioned, now there's no error, but Hyper wouldn't start...

```
➜  .hyper_plugins rm -rf ./node_modules 
➜  .hyper_plugins npm i
➜  .hyper_plugins cat node_modules/hyper-material-theme/package.json | grep version
  "version": "2.0.5"
```

**Comment by equinusocio** [comment]
@yurynix Can you try with yarn? Remove also package-lock.json
-`rm -r node_modules package-lock.json`
-`yarn`

**Comment by yurynix** [comment]
I don't have a `package-lock.json`
```
➜  .hyper_plugins node -v && npm -v
v6.10.3
3.10.10
➜  .hyper_plugins npm i -g yarn
➜  .hyper_plugins yarn   
yarn install v0.24.5
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "0.24.6" while you're on "0.24.5".
info To upgrade, run the following command:
$ npm upgrade --global yarn
✨  Done in 8.52s.
➜  .hyper_plugins 
```

Same thing with yarn

**Comment by equinusocio** [comment]
You shoud have the package-lock.json.. i think we have to wait

**Comment by yurynix** [comment]
`package-lock.json` is an npm 5 thing, and I have npm 3, so there shouldn't be =)

**Comment by equinusocio** [comment]
Yes, but you should not have issue using npm 3... so i don't know why your hyper does not start.

**Comment by Sgouws** [comment]
It's worth noting that if you are using WSL you will have to install node separately within WSL in order to get this theme working properly.

```
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs
```

**After this is done. Follow equinusocio's advice:**
1. Remove hyper-material-theme from your plugins list
2. Restart hyper
3. Add again hyper-material-theme
4. Restart again

**Comment by RemiVillien** [comment]
Thanks, I works now ;D
But i don't have any Vibrancy :0

**Comment by foisonocean** [comment]
I followed EDIT 3, but it still doesn't work for me.
![2017-08-05 12_54_28](https://user-images.githubusercontent.com/15059605/28992956-42693e44-79dd-11e7-8041-2b2a923acdd0.gif)

**Comment by equinusocio** [comment]
@foisonocean You have to remove also the package-lock file:
> cd ~/.hyper_plugins
> rm -r node_modules package-lock.json
> npm i --no-shrinkwrap

**Comment by foisonocean** [comment]
@equinusocio I have removed `package-lock.json`, see my gif.

**Comment by equinusocio** [comment]
After removing the node_modules and after npm i check if node_modules contains your plugins

**Comment by foisonocean** [comment]
@equinusocio 
Yes, it contains the `hyper-material-theme` plugin in the node_modules. I am so confused about why this doesn't work.

**Comment by derrickpelletier** [comment]
I've followed these various solutions as well and am also experiencing hyper not loading any GUI.

**Comment by equinusocio** [comment]
@derrickpelletier more info here https://github.com/zeit/hyper/issues/191

**Comment by alexmccabe** [comment]
Hyper has just been updated to better support plugins, however this plugin still crashes the app on load.

**Comment by equinusocio** [comment]
@alexmccabe i can't reproduce your situation. With 1.4.5 on mac i have no issues anymore.

**Comment by alexmccabe** [comment]
@equinusocio where did you get 1.4.5, as 1.4.2 was the version that just got released. But I _still_ can't get it to work. I have emptied the directories suggested, I have also completely removed the `~/.hyper_plugins` directory, then manually installed with `npm install`, but no luck.

**Comment by equinusocio** [comment]
@alexmccabe Sorry, now i have 1.4.3 and i tried removing all plugins and then add them one by one, including material theme. All works like before. Try to purge again `node_modules`, `package-lock` and empty `package.json`.

Anyone can test the installation?

**Comment by alexmccabe** [comment]
@equinusocio Unfortunately not. Updated Hyper to 1.4.3, removed `node_modules` and `package-lock.json`, removed all plugins from my `.hyper.js` config file. 

Added `hyper-material-theme` back in
```
plugins: [
    'hyper-material-theme'
],
```

and it still crashes Hyper on launch.

**Comment by equinusocio** [comment]
You get an error?

**Comment by alexmccabe** [comment]
No errors, the app just doesn't launch. It will claim it is open, but there are no menu items aside from the **Hyper** one, which only allows me to quit.
![screenshot 2017-09-04 14 02 34](https://user-images.githubusercontent.com/2529110/30027635-b6c82378-9179-11e7-85fb-76df4d09ea5f.png)

**Comment by equinusocio** [comment]
This is very strange because this issue was related to a console error throw by any installed plugins. This issue is new for me and i can't reproduce it. Have you tried to reinstall hyper?

**Comment by alexmccabe** [comment]
I just nuked Hyper; removed app, preferences and plugins, reinstalled Hyper and still have the same issue.

**Comment by equinusocio** [comment]
I need feedbacks from other @RemiVillien @senorsancho @nonsocode @derrickpelletier @foisonocean

**Comment by MattHoneycutt** [comment]
Same thing happens to me, too.  Tried the workarounds and suggestions, still nothing.  This is on Windows 10.

**Comment by chabou** [comment]
Your issue is here: https://github.com/equinusocio/hyper-material-theme/blob/master/index.js#L9

Users shouldn't have a `config.MaterialTheme` section in their `.hyper.js`.
You should have a default config and merge user config. It will work out of the box.

**Comment by MattHoneycutt** [comment]
@chabou is right.  Once I added a MaterialTheme section to my config, the plugin started working again.

**Comment by equinusocio** [comment]
@chabou At the moment i have no time to work on this fix. If you have some time PR are welcome.

**Comment by equinusocio** [comment]
Release 2.0.6 is out.
