### ISSUE TITLE
Installation instructions are incomplete

### ISSUE THREAD

**Issue by codeams** [equinusocio/hyper-material-theme#21]
If you add the theme to a fresh installation of Hyper an exception is raised: "Cannot read property theme of null". Solved it adding the material theme configuration object to `~/.hyper.js`.

I think the read me isn't clear enough about this. It makes me think the app will work even if there is no custom configuration. Maybe it should work without a configuration object or maybe we need to make the installation instructions a little bit clearer.

Currently using the Palenight theme in Sublime, VSCode and Hyper. Love it ♥︎.

**Comment by equinusocio** [comment]
You are right. I will fix that. PR are welcome.

Il sab 1 lug 2017, 04:31 Erick A. Montañez <notifications@github.com> ha
scritto:
