### ISSUE TITLE
Opacity does not work

### ISSUE THREAD

**Issue by Lotok** [equinusocio/hyper-material-theme#24]
Hey

i tried too change `backgroundOpacity` but nothing changes.

My config:
`
// Future versions of Hyper may add additional config options,
// which will not automatically be merged into this file.
// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    // default font size in pixels for all tabs
    fontSize: 12,

    // font family with optional fallbacks
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',

    // terminal cursor background color and opacity (hex, rgb, hsl, hsv, hwb or cmyk)
    cursorColor: 'rgba(248,28,229,0.8)',

    // `BEAM` for |, `UNDERLINE` for _, `BLOCK` for █
    cursorShape: 'BLOCK',

    // set to true for blinking cursor
    cursorBlink: true,

    // color of the text
    foregroundColor: '#33ff00',

    // terminal background color
    backgroundColor: '#000',

    // border color (window, tabs)
    borderColor: '#333',

    // custom css to embed in the main window
    css: '',
	
    // custom css to embed in the terminal window
    termCSS: '',

    // set to `true` (without backticks) if you're using a Linux setup that doesn't show native menus
    // default: `false` on Linux, `true` on Windows (ignored on macOS)
    showHamburgerMenu: '',

    // set to `false` if you want to hide the minimize, maximize and close buttons
    // additionally, set to `'left'` if you want them on the left, like in Ubuntu
    // default: `true` on windows and Linux (ignored on macOS)
    showWindowControls: '',

    // custom padding (css format, i.e.: `top right bottom left`)
    padding: '12px 14px',

    // the full list. if you're going to provide the full color palette,
    // including the 6 x 6 color cubes and the grayscale map, just provide
    // an array here instead of a color map object
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },

	MaterialTheme: {
        // Set the theme variant, 
        // OPTIONS: 'Darker', 'Palenight', '' 
        theme: '',
 
        // Set the rgba() app background opacity, useful when enableVibrance is true 
        // OPTIONS: From 0.1 to 1 
        backgroundOpacity: '0.6',
 
        // Set the accent color for the current active tab 
        accentColor: '#33ff00',
 
        // Mac Only. Need restart. Enable the vibrance and blurred background 
        // OPTIONS: 'dark', 'ultra-dark', 'bright' 
        // NOTE: The backgroundOpacity should be between 0.1 and 0.9 to see the effect. 
        vibrancy: 'ultra-dark'
    },
	
    // the shell to run when spawning a new session (i.e. /usr/local/bin/fish)
    // if left empty, your system's login shell will be used by default
    // make sure to use a full path if the binary name doesn't work
    // (e.g `C:\\Windows\\System32\\bash.exe` instead of just `bash.exe`)
    // if you're using powershell, make sure to remove the `--login` below
    shell: '',

    // for setting shell arguments (i.e. for using interactive shellArgs: ['-i'])
    // by default ['--login'] will be used
    shellArgs: ['--login'],

    // for environment variables
    env: {},

    // set to false for no bell
    bell: 'SOUND',

    // if true, selected text will automatically be copied to the clipboard
    copyOnSelect: false

    // if true, on right click selected text will be copied or pasted if no
    // selection is present (true by default on Windows)
    // quickEdit: true

    // URL to custom bell
    // bellSoundURL: 'http://example.com/bell.mp3',

    // for advanced config flags please refer to https://hyper.is/#cfg
  },

  // a list of plugins to fetch and install from npm
  // format: [@org/]project[#version]
  // examples:
  //   `hyperpower`
  //   `@company/project`
  //   `project#1.0.1`
  plugins: [
  'hyper-material-theme'
],

  // in development, you can create a directory under
  // `~/.hyper_plugins/local/` and include it here
  // to load it and avoid it being `npm install`ed
  localPlugins: []
};
`

![image](https://user-images.githubusercontent.com/28544189/29863274-71d81290-8d6f-11e7-88e0-3b8f03f464e6.png)

And is it possible to change the foreground color with the theme on?

**Comment by equinusocio** [comment]
Opacity only work on MacOS.

**Comment by aequasi** [comment]
Im not getting opacity to work on macOS either.

**Comment by flekschas** [comment]
Same here. Looks like `backgroundOpacity` doesn't do anything. Any updates?

**Comment by DRSDavidSoft** [comment]
Related discussion: https://github.com/zeit/hyper/issues/1638
Basically this is needed: https://github.com/electron/electron/issues/11771

**Comment by NansD** [comment]
It does work for me on Windows ! 
Here is my config : 
``` module.exports = {
  config: {
    // choose either `'stable'` for receiving highly polished,
    // or `'canary'` for less polished but more frequent updates
    updateChannel: 'stable',

    opacity: 0.95, ```

**Comment by equinusocio** [comment]
Hi all, this theme will be completely rewritten after the May release of [Material Theme for VSC](https://equinsuocha.io/projects/material-theme/)
