### ISSUE TITLE
Screenshot shows shell highlighting

### ISSUE THREAD

**Issue by drewswaycool** [equinusocio/hyper-material-theme#25]
<img width="613" alt="bbaf728e-c31a-11e6-972f-0995e77a32a0" src="https://user-images.githubusercontent.com/3419661/29989457-44cd703e-8f30-11e7-9b22-a972abe65677.png">

In the screenshot in the readme shell highlighting is included. Can you provide information as to what shell highlighting you are using and also any other plugins that compliment this extension?

**Comment by equinusocio** [comment]
I'm using zsh with OhMyZsh framework.
