### ISSUE TITLE
Activate theme is disabled !

### ISSUE THREAD

**Issue by iamslimane** [equinusocio/hyper-material-theme#30]
### Hi @equinusocio ,
I have a problem that i can't activate the material theme ! i tried two methods and they didn't work !

### The 1st method :

> `ctrl` + `shift` + `p` `:` `material theme`.

As you see i only got : `Advanced Configuration` ! 

I should get also `Activate Theme` when i type `material Theme`.

![2s](https://user-images.githubusercontent.com/31626673/34352816-fec36b2a-ea24-11e7-80a6-e729357fd1ff.PNG)

### The 2nd method :

> `Preferences` > `Package Settings` > `Material Theme`

As you see `Activate` is disabled !

![capture](https://user-images.githubusercontent.com/31626673/34352817-fee6f144-ea24-11e7-9c97-2b2880b9c84e.PNG)

## This is the only problem that i have !

Thanks for your attention and have a great day !

**Comment by radko79** [comment]
Hey, looks like we are both sitting on the same problem and no-one else in the whole wide world!

**Comment by equinusocio** [comment]
Hi, this is the hyper material theme repository.

**Comment by radko79** [comment]
OK, thanks for reply. For anyone having the same issue and getting stuck I prepared my user preferances. Hope, someone can benefit someday. 
Just open advanced configuration and paste below code:

"always_show_minimap_viewport": true,
	"bold_folder_labels": true,
	"color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
	"font_face": "Fira Code",
	"font_size": 13,
	"ignored_packages":
	[
		"Emmet",  // if you have this package installed
		"Vintage"
	],
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 3,
	"line_padding_top": 3,
	"margin": 0,
	"material_theme_compact_panel": true,
	"material_theme_compact_sidebar": true,
	"material_theme_contrast_mode": true,
	"material_theme_disable_fileicons": false,
	"material_theme_disable_folder_animation": false,
	"material_theme_disable_tree_indicator": false,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"material_theme_tabs_autowidth": true,
	"overlay_scroll_bars": "enabled",
	"theme": "Material-Theme-Darker.sublime-theme"
}"

Feel free to toggle between false/true values. Save and check the result. Somehow it enabled other settings. Cheers!

**Comment by hsntngr55** [comment]
@radko79  thank you for sharing this :)

**Comment by lexhaynes** [comment]
A HUGE THANKS to radko79!

I know Material Theme is deprecated, but it usually works just fine until some package updates.
