### ISSUE TITLE
How to change username color to red like in ReadMe screenshot?

### ISSUE THREAD

**Issue by iamvinny** [equinusocio/hyper-material-theme#31]
In the ReadMe screenshot the username is red

![ReadMe Screenshot](https://cloud.githubusercontent.com/assets/10454741/21243792/bbaf728e-c31a-11e6-972f-0995e77a32a0.png)

I installed the theme following the instructions, but mine is white. 

![ReadMe Screenshot](https://i.imgur.com/zclV2T8.png)

Is there a way to change it ?

Here is my hyper.js

https://pastebin.com/EGdxeSpg

**Comment by Rawnly** [comment]
You need to change your $PS1, you can read more about it [here](https://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html).

I suggest [to install the **ZSH** shell](https://github.com/robbyrussell/oh-my-zsh/wiki/Installing-ZSH) + [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh)
