### ISSUE TITLE
Shortcuts don't show with opacity below 1

### ISSUE THREAD

**Issue by ttches** [equinusocio/hyper-material-theme#36]
With backgroundOpacity set below 1, shortcut commands show white text on a white background.

<img width="953" alt="screen shot 2018-04-27 at 2 40 50 pm" src="https://user-images.githubusercontent.com/15929691/39386599-4b7ae6fe-4a2a-11e8-9294-7eb5a4c4bc46.png">

**Comment by equinusocio** [comment]
Can you try with the latest relase?

**Comment by equinusocio** [comment]
Hi, can you report this issue to the hyper team?
