### ISSUE TITLE
Warning: "hyper-material-theme" plugin uses some deprecated CSS classes (x-screen, ::selection).

### ISSUE THREAD

**Issue by pdxfalls** [equinusocio/hyper-material-theme#37]
This warning shows in developer tools and causes a "plugin error" notification to pop up.

`Warning: "hyper-material-theme" plugin uses some deprecated CSS classes (x-screen, ::selection).`

Please use the CSS classes made to replace these.

**Comment by scheMeZa** [comment]
Please, this popup gets annoying

**Comment by equinusocio** [comment]
@pdxfalls 
> Please use the CSS classes made to replace these.

Where they are documented?

**Comment by equinusocio** [comment]
Can you check with the latest update?

**Comment by scheMeZa** [comment]
I can confirm that I'm no longer getting the warning in the console. Thank you.
