### ISSUE TITLE
No color syntax are showing just a plain hyper cmd

### ISSUE THREAD

**Issue by ReactorboY** [equinusocio/hyper-material-theme#41]
First time user of Hyper, installed your theme using 
```
hyper i hyper-material-theme
```
still no theme colour are showing just plain white colour syntax nothing else
![Screenshot (20)](https://user-images.githubusercontent.com/18748533/56262856-2a59d200-60fe-11e9-8a39-2e47c42e089b.png)

Using
Window : 8.1
Hyper : 2.1.2

**Comment by equinusocio** [comment]
Text colours are not provided by this theme. You should use a console like zsh and enable colors.
