### ISSUE TITLE
Border Color on Main window after 3.0 update

### ISSUE THREAD

**Issue by osbornm** [equinusocio/hyper-material-theme#42]
The border color is now transparent after updating to 3.0 (see screenshot).  When the plugin is first installed it looks correct but after a restart the border goes transparent. I assume something changed in the markup sine this is a major release. I have no custom CSS installed and have verified my preference are "default" to a new hyper install. 

<img width="1371" alt="Screen Shot 2019-05-06 at 9 00 25 AM" src="https://user-images.githubusercontent.com/674284/57230427-f6c3e680-6fdd-11e9-9273-040ac83011bb.png">

**Comment by Favna** [comment]
Went to the repo to create an issue only to find this one so instead I'm just confirming it. MacOS Mojave 10.14.4, Hyper 3.0.

![image](https://user-images.githubusercontent.com/4019718/57231014-f47f7d80-7019-11e9-9c5d-53607a1ca945.png)

**Comment by hughes** [comment]
Also confirming that removing hyper-material-theme resolves the issue.

**Comment by Krato** [comment]
Yes, but If we want to use it?

**Comment by Favna** [comment]
Either don't update Hyper to 3.0 or use another theme @Krato

**Comment by LasaleFamine** [comment]
Hi there, this (and others) should be fixed with the new release upcoming for Hyper 3. Please be patient, PR is already opened #43

**Comment by equinusocio** [comment]
I released the 3.0.0. Please let us know if the issue persist.

**Comment by osbornm** [comment]
@equinusocio verified and fixed.
