### ISSUE TITLE
Background color for some strings

### ISSUE THREAD

**Issue by pferretti** [equinusocio/hyper-material-theme#5]
I don't know if it's a bug or a feature, but when I use npm, I got something like this:

<img width="388" alt="screen shot 2017-02-09 at 10 48 11" src="https://cloud.githubusercontent.com/assets/1481654/22778010/84b940ae-eeb5-11e6-9e85-a7bfd660be2e.png">

with the background color of package names that is different from the the background color of the terminal.

**Comment by thunsaker** [comment]
Apparently this is a feature of npm. Found the following on npm repo: https://github.com/npm/npm/issues/10208

> The highlighted packages are the ones that have been updated or moved as part of the current install operation. You're right that it's underdocumented behavior, so I've marked it as a documentation bug. Once you know how to read it, it's very useful information, but it took me a while, and I help maintain the CLI. via [othiym23](https://github.com/npm/npm/issues/10208#issuecomment-161467337)
