### ISSUE TITLE
backgroundOpacity with enableVibrance doesn't seem to be working?

### ISSUE THREAD

**Issue by sumnermic** [equinusocio/hyper-material-theme#6]
Hello,

I am unable to set the `backgroundOpacity` and `enableVibrance` for the latest version 1.2.1 of HyperTerm.

I run on Mac 10.12.3.

If possible I'd like to ask for your .hyper.js maybe if I can replicate it here it should work?

For reference, please see [my .hyper.js file here](https://gist.github.com/sumnermic/d634be7444edadd75f2b4bec759b5bd6).

Kind regards,

Mic

**Comment by Rawnly** [comment]
See #4 , try to puts settings under the colro object.
