### ISSUE TITLE
Unknown configurations

### ISSUE THREAD

**Issue by carlosvigil** [equinusocio/hyper-material-theme#9]
Using the supplied code for vibrancy etc., makes Hyper reset the entire hyperjs file. I tried commenting  out each one but they all return that they aren't recognized.

**Comment by Rawnly** [comment]
Have you seen #6 & #4 ? Puts configs under the `colors` object

**Comment by carlosvigil** [comment]
Thanks, should really update the readme as I had to find a backup config. I'll pr in a minute.

**Comment by Rawnly** [comment]
Here a little tip to prevent this types of problems:

After saving the *.hyper.js* don't close the editor, (I've tested it only on atom) if the file reset, hit <kbd>ctrl/CMDv+ Z</kbd> or whatelse and should be back the personalization. @carlosvigil :)
